permalink: /:year/:title

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      _hide_content: true
      permalink: /posts/:slug

collections:
  projects:
    output: true
  archives:
    output: true
  services:
    output: true

sizes:
  - full
  - one-half
  - one-third
  - two-thirds

aspect-ratios:
  - portrait
  - portrait-tall
  - square
  - landscape

column-sizes:
  - col-2_sm-12
  - col-3_sm-12
  - col-4_sm-12

block-classes:
  - light-bg
  - featured-bg
  - dark-bg
  - padded-1
  - padded-2
  - padded-5p
  - border-center
  - bg-split-white-tan
  - bg-split-tan-white
  - bg-v-white-tan

inner-block-classes:
  - light-bg
  - featured-bg
  - dark-bg
  - padded-1
  - padded-2
  - padded-5p
  - border-center
  - bg-split-white-tan
  - bg-split-tan-white
  - bg-v-white-tan

_options:
  heading_html:
    format: p h1 h2 h3 h4 h5 h6
    right: align-to-right
    center: align-to-center
    left: align-to-left
    bold: true
    italic: true
    link: true
    styles: /assets/editor.css
  body-content_html:
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
    image: true
    bulletedlist: true
    styles: /assets/editor.css
  content:
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
    image: true
    bulletedlist: true
    styles: /assets/editor.css

sass:
    sass_dir: _sass

page_blocks: []
_array_structures:
  page_blocks:
    - label: Flexible Cols
      icon: format_quote
      value:
        _id: cols
        block-classes:
        heading_html:
        columns: []
    - label: Gallery
      icon: format_quote
      value:
        _id: gallery
        block-classes:
        heading_html:
        gallery-images: []
        gallery-text_html:
    - label: Text Block
      icon: format_quote
      value:
        _id: text-block
        block-classes:
        inner-block-classes:
        content_html:
  columns:
    label: Column
    icon: collections
    value:
      column-size:
      class:
      text_html:
  gallery-images:
    label: Gallery Images
    icon: collections
    value:
      image_path:
      aspect-ratio:
